language: java

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  sonarcloud:
    organization: "krishnawisely"
    token:
      secure: 5e09c837bf6edd1ed6f2faf29cc8083b951cc557 # encrypted value of your token

script:
  - ./gradlew sonarqube -Dsonar.projectKey=krishnawisely_eresume
notifications:
  email:
    recipients:
      - krishna192168@gmail.com
    on_success: never # default: change
    on_failure: always # default: always